steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      token: ${{ secrets.GITHUB_TOKEN }}

  - name: Make a dummy change
    run: |
      echo "Last run on $(date -u)" > daily_commit_log.txt

  - name: Commit and push changes for email 24f2000216@ds.study.iitm.ac.in
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      git config --global user.name "GitHub Actions Bot"
      git config --global user.email "24f2000216@ds.study.iitm.ac.in"
      git add daily_commit_log.txt
      git commit -m "Automated daily commit on $(date -u)" || echo "No changes to commit"
      git pull origin main --rebase
      git push origin HEAD:main
